name: Get Data from API and Create File
on:
  push:
    branches:
      - main

jobs:
  get_data_and_create_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get data from API and create files
        run: |
          url="http://api.open-notify.org/iss-now.json"
          data=$(curl -s "$url")

          if [ "$data" ]; then
            timestamp=$(date +'%Y-%m-%d_%H-%M-%S')
            filename_json="data_$timestamp.json"
            filename_html="data_$timestamp.html"
            file_path_json="$GITHUB_WORKSPACE/$filename_json"
            file_path_html="$GITHUB_WORKSPACE/$filename_html"

            echo "$data" > "$file_path_json"
            echo "Data successfully written to $file_path_json"

            # Convert JSON to HTML
            echo "<html><body><pre>" > "$file_path_html"
            cat "$file_path_json" >> "$file_path_html"
            echo "</pre></body></html>" >> "$file_path_html"

            echo "Data successfully written to $file_path_html"
          else
            echo "Failed to retrieve data from the API."
          fi

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
