name: Get Data from API and Create File
on:
  push:
    branches:
      - main

jobs:
  get_data_and_create_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create directory if it doesn't exist
        run: mkdir -p $GITHUB_WORKSPACE/iss_data

      - name: Get data from API and create files
        run: |
          url="http://api.open-notify.org/iss-now.json"
          data=$(curl -s "$url")

          if [ "$data" ]; then
            timestamp=$(date +'%Y-%m-%d_%H-%M-%S')
            filename_json="data_$timestamp.json"
            file_path_json="$GITHUB_WORKSPACE/iss_data/$filename_json"

            echo "$data" > "$file_path_json"
            echo "Data successfully written to $file_path_json"
          else
            echo "Failed to retrieve data from the API."
          fi

      - name: Get data from API and create files
        run: |
          url="http://api.open-notify.org/iss-now.json"
          data=$(curl -s "$url")

          if [ "$data" ]; then
            timestamp=$(date +'%Y-%m-%d_%H-%M-%S')
            filename_json="data_$timestamp.json"
            file_path_json="$GITHUB_WORKSPACE/iss_data/$filename_json"

            echo "$data" > "$file_path_json"
            echo "Data successfully written to $file_path_json"
          else
            echo "Failed to retrieve data from the API."
          fi

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          publish_repo: ashwinkumaar/nus-devops-project
          full_commit_message: Deployed to GitHub Pages
          cname: yourcustomdomain.com # Add your custom domain here, if applicable
