name: Get Data from API and Create File
on:
  push:
    branches:
      - main

jobs:
  get_data_and_create_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get data from API and create file
        run: |
          url="http://api.open-notify.org/iss-now.json"
          data=$(curl -s "$url")

          if [ "$data" ]; then
            timestamp=$(date +'%Y-%m-%d_%H-%M-%S')
            filename="data_$timestamp.json"
            file_path="$GITHUB_WORKSPACE/$filename"

            echo "$data" > "$file_path"
            echo "Data successfully written to $file_path"
          else
            echo "Failed to retrieve data from the API."
          fi

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add data file from API"
          git push
